
project_id = "bwxvudskpkzzfrohntaq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.process-assistant-query]

[edge_functions.google-transcribe]

[edge_functions.vertex-ai-assistant]

[edge_functions.create-subscription]

[edge_functions.check-subscription]

[edge_functions.stripe-webhook]
verify_jwt = false

[edge_functions.oauth2-token]

