
project_id = "bwxvudskpkzzfrohntaq"

[functions.process-assistant-query]
verify_jwt = true

[functions.vertex-ai-assistant]
verify_jwt = true

[functions.meeting-export]
verify_jwt = true

[functions.google-transcribe]
verify_jwt = true

[functions.multi-language-transcribe]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.analytics-insights]
verify_jwt = true
